eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      defaultZone: http://host.docker.internal:8761/eureka
okta:
  oauth2:
    issuer: https://dev-26096474.okta.com/oauth2/default
    audience: api://default
